import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`bg-black md:border md:rounded-md md:border-gray-800  md:p-5 my-5 max-w-[800px] mx-auto p-5 text-white `}
      >
        {children}
      </body>
    </html>
  );
}
